---
title: "01. Lexical statistics. Excercises"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1.0 Загрузить текстовые данные в R из CSV — коллекция анекдотов о
школе в файле `eu2022/data/school.csv`.

1.1 Выполнить токенизацию данных (простую пословную) с помощью
*tidytext*.

1.2 Построить частотный список слов по анекдотам. Построить график
частотность—ранг в простой и логарифмической шкалах.

1.4 Какую частотность предсказывает закон Ципфа для второго и третьего
слова в частнотном списке и как эта частотность соотносится с
фактической частотностью в данных?

1.5 Какова средняя и медианная частотность слова в данных по
Государственной Думе? По анекдотам? Как они изменятся, если взять в качестве данных
только первую половину текста? Объясните, почему.

1.6 Если добавить в коллекцию еще столько же анекдотов, насколько
увеличится размер словаря?

1.7 Вычислите оценку скорости роста словаря по Бааену для данных по
Государственной Думе. Постройте график изменения этой величины для каждого из
128 заседаний сессии.



