---
title: "02 Препроцессинг. Упражнения"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

2.1. Выберите фрагмент данных по Государственной Думе (например, любую
сессию) и составьте частотный список биграмм, не включающих
стоп-слов. В дальнейших упражнениях используйте этот же фрагмент
данных по ГД.

2.2. Cоставьте частотный список триграмм. Профильтруйте список таким
образом, чтобы в нем остались только триграммы, в которых присутствует
хотя бы одно слово не из списка стоп-слов.

2.3. Проведите лемматизацию текстов и постройте частотный список
лемм (не удаляя стоп-слова). Сравните первые 150 слов этом частотном
списке и «стандартный» список стоп-слов для русского языка из пакета
stopwords. Какие слова из топ-списка частотных в данных по ГД
отсутствуют в «стандартном» списке? Следует ли эти слова рассматривать
как стоп-слова при анализе данных по ГД? Есть ли в «стандартном»
списке слова, которые отсутствуют в топ-списке частотных слов? 

2.4. Лемматизируйте данные таким образом, чтобы сохранить не только
леммы, но и части речи. Составьте частотные списки прилагательных и
глаголов. 

